PINYIN = {'A0':u'A','A1':u'\u0100','A2':u'\xc1','A3':u'\u01cd','A4':u'\xc0','A5':u'A',
          'a0':u'a','a1':u'\u0101','a2':u'\xe1','a3':u'\u01ce','a4':u'\xe0','a5':u'a',
          'E0':u'E','E1':u'\u0112','E2':u'\xc9','E3':u'\u011a','E4':u'\xc8','E5':u'E',
          'e0':u'e','e1':u'\u0113','e2':u'\xe9','e3':u'\u011b','e4':u'\xe8','e5':u'e',
          'I0':u'I','I1':u'\u012a','I2':u'\xcd','I3':u'\u01cf','I4':u'\xcc','I5':u'I',
          'i0':u'i','i1':u'\u012b','i2':u'\xed','i3':u'\u01d0','i4':u'\xec','i5':u'i',
          'O0':u'O','O1':u'\u014c','O2':u'\xd3','O3':u'\u01d1','O4':u'\xd2','O5':u'O',
          'o0':u'o','o1':u'\u014d','o2':u'\xf3','o3':u'\u01d2','o4':u'\xf2','o5':u'o',
          'U0':u'U','U1':u'\u016a','U2':u'\xda','U3':u'\u01d3','U4':u'\xd9','U5':u'U',
          'u0':u'u','u1':u'\u016b','u2':u'\xfa','u3':u'\u01d4','u4':u'\xf9','u5':u'u',
          'V0':u'\u00dc','V1':u'\u01d5','V2':u'\u01d7','V3':u'\u01d9','V4':u'\u01db','V5':u'\u00dc',
          'v0':u'\u00fc','v1':u'\u01d6','v2':u'\u01d8','v3':u'\u01da','v4':u'\u01dc','v5':u'\u00fc'}

CONV = {'cún': 'cun2', 'zǎ': 'za3', 'bāi': 'bai1', 'mǔ': 'mu3',
'tiào': 'tiao4', 'suàn': 'suan4', 'sàn': 'san4', 'wěi': 'wei3', 'yuè': 'yue4',
'né': 'ne2', 'hǒng': 'hong3', 'mǒu': 'mou3', 'yo': 'yo', 'bò': 'bo4',
'mōu': 'mou1', 'dǐ': 'di3', 'shǎo': 'shao3', 'cán': 'can2', 'dá': 'da2',
'guài': 'guai4', 'pí': 'pi2', 'biè': 'bie4', 'suī': 'sui1', 'shóu': 'shou2',
'cū': 'cu1', 'zhǎng': 'zhang3', 'xuě': 'xue3', 'yāng': 'yang1', 'gòu': 'gou4',
'chěng': 'cheng3', 'diē': 'die1', 'hóng': 'hong2', 'pǎng': 'pang3',
'tuī': 'tui1', 'zhū': 'zhu1', 'àn': 'an4', 'yín': 'yin2', 'shèn': 'shen4',
'dǐng': 'ding3', 'huà': 'hua4', 'zhào': 'zhao4', 'jiu': 'jiu', 'kǔn': 'kun3',
'juǎn': 'juan3', 'pāng': 'pang1', 'lì': 'li4', 'chuò': 'chuo4', 'bàn': 'ban4',
'chāo': 'chao1', 'piāo': 'piao1', 'suì': 'sui4', 'dà': 'da4', 'gěn': 'gen3',
'chóng': 'chong2', 'xiǔ': 'xiu3', 'shāo': 'shao1', 'qǐ': 'qi3', 'fàn': 'fan4',
'yóng': 'yong2', 'jìng': 'jing4', 'tián': 'tian2', 'chuān': 'chuan1',
'gū': 'gu1', 'zè': 'ze4', 'kēng': 'keng1', 'něi': 'nei3', 'kuà': 'kua4',
'pēi': 'pei1', 'làng': 'lang4', 'chǒng': 'chong3', 'yō': 'yo1',
'zhèi': 'zhei4', 'miǎn': 'mian3', 'chuái': 'chuai2', 'kēi': 'kei1',
'tǎ': 'ta3', 'páo': 'pao2', 'zhā': 'zha1', 'fēi': 'fei1', 'hū': 'hu1',
'diū': 'diu1', 'bēn': 'ben1', 'chèn': 'chen4', 'pǐ': 'pi3',
'shuǎng': 'shuang3', 'nāng': 'nang1', 'cuī': 'cui1', 'dí': 'di2',
'jiā': 'jia1', 'zhuān': 'zhuan1', 'bí': 'bi2', 'tōu': 'tou1', 'rùn': 'run4',
'hòng': 'hong4', 'hōu': 'hou1', 'tuàn': 'tuan4', 'diāo': 'diao1',
'méi': 'mei2', 'yáng': 'yang2', 'cuō': 'cuo1', 'zǒng': 'zong3',
'tòng': 'tong4', 'dōng': 'dong1', 'tuì': 'tui4', 'zhàn': 'zhan4',
'sǎn': 'san3', 'fà': 'fa4', 'jiá': 'jia2', 'xián': 'xian2', 'nè': 'ne4',
'zuàn': 'zuan4', 'liǎo': 'liao3', 'yuān': 'yuan1', 'zān': 'zan1', 'kè': 'ke4',
'chán': 'chan2', 'chì': 'chi4', 'zǒu': 'zou3', 'gǎ': 'ga3', 'huàn': 'huan4',
'guǎng': 'guang3', 'yòu': 'you4', 'kuǎ': 'kua3', 'liě': 'lie3', 'me': 'me',
'chòng': 'chong4', 'mào': 'mao4', 'ō': 'o1', 'běng': 'beng3', 'téng': 'teng2',
'chǎng': 'chang3', 'shuài': 'shuai4', 'bá': 'ba2', 'zuò': 'zuo4',
'sòu': 'sou4', 'chuàng': 'chuang4', 'niǎn': 'nian3', 'fèn': 'fen4',
'zán': 'zan2', 'zuō': 'zuo1', 'nòu': 'nou4', 'nǎi': 'nai3', 'zǎn': 'zan3',
'māo': 'mao1', 'qu': 'qu', 'dǎ': 'da3', 'xún': 'xun2', 'jīn': 'jin1',
'pǒu': 'pou3', 'zhī': 'zhi1', 'ruǐ': 'rui3', 'dāi': 'dai1', 'báo': 'bao2',
'pāi': 'pai1', 'shuāi': 'shuai1', 'chào': 'chao4', 'bèn': 'ben4',
'pōu': 'pou1', 'yán': 'yan2', 'bāng': 'bang1', 'liào': 'liao4',
'sǒng': 'song3', 'zuān': 'zuan1', 'zài': 'zai4', 'mán': 'man2',
'sòng': 'song4', 'zāng': 'zang1', 'fèi': 'fei4', 'de': 'de', 'tāng': 'tang1',
'tūn': 'tun1', 'shá': 'sha2', 'kèn': 'ken4', 'àng': 'ang4', 'pīn': 'pin1',
'bīn': 'bin1', 'qū': 'qu1', 'kān': 'kan1', 'pìn': 'pin4', 'gēng': 'geng1',
'yuán': 'yuan2', 'chǔn': 'chun3', 'ruǎn': 'ruan3', 'chǎo': 'chao3',
'cèng': 'ceng4', 'xiè': 'xie4', 'diào': 'diao4', 'fěi': 'fei3',
'kǒng': 'kong3', 'tā': 'ta1', 'nóng': 'nong2', 'ké': 'ke2', 'zhǐ': 'zhi3',
'huī': 'hui1', 'lún': 'lun2', 'chā': 'cha1', 'piě': 'pie3', 'bǎi': 'bai3',
'qíng': 'qing2', 'yìn': 'yin4', 'lào': 'lao4', 'jiè': 'jie4', 'juàn': 'juan4',
'lī': 'li1', 'há': 'ha2', 'rě': 're3', 'bìng': 'bing4', 'shēng': 'sheng1',
'gěng': 'geng3', 'pā': 'pa1', 'liǎng': 'liang3', 'shěn': 'shen3', 'òu': 'ou4',
'zhěng': 'zheng3', 'yǐ': 'yi3', 'tiǎn': 'tian3', 'léi': 'lei2',
'chuán': 'chuan2', 'xiào': 'xiao4', 'qì': 'qi4', 'ǎn': 'an3', 'lǔn': 'lun3',
'kūn': 'kun1', 'zhá': 'zha2', 'fāng': 'fang1', 'děng': 'deng3', 'hùn': 'hun4',
'tuí': 'tui2', 'qiě': 'qie3', 'cuǒ': 'cuo3', 'liāo': 'liao1', 'tài': 'tai4',
'měi': 'mei3', 'biē': 'bie1', 'wán': 'wan2', 'hái': 'hai2', 'quán': 'quan2',
'zhūn': 'zhun1', 'lüē': 'lüe1', 'niǔ': 'niu3', 'zhuì': 'zhui4', 'gěi': 'gei3',
'shī': 'shi1', 'pú': 'pu2', 'hǒu': 'hou3', 'zhǎ': 'zha3', 'luàn': 'luan4',
'yuǎn': 'yuan3', 'sù': 'su4', 'lei': 'lei', 'à': 'a4', 'mēn': 'men1',
'wǎn': 'wan3', 'zhú': 'zhu2', 'mēng': 'meng1', 'chūn': 'chun1', 'liǎ': 'lia3',
'lǐn': 'lin3', 'ě': 'e3', 'qiǎo': 'qiao3', 'tǐ': 'ti3', 'bǐ': 'bi3',
'tuǐ': 'tui3', 'rǔ': 'ru3', 'dòng': 'dong4', 'wō': 'wo1', 'shé': 'she2',
'nàng': 'nang4', 'pǒ': 'po3', 'méng': 'meng2', 'yuē': 'yue1', 'quǎn': 'quan3',
'tuǎn': 'tuan3', 'féi': 'fei2', 'xuàn': 'xuan4', 'pāo': 'pao1', 'jū': 'ju1',
'luó': 'luo2', 'huàng': 'huang4', 'dē': 'de1', 'jǐng': 'jing3', 'rǎn': 'ran3',
'yóu': 'you2', 'huò': 'huo4', 'sāng': 'sang1', 'tān': 'tan1', 'ráng': 'rang2',
'kuí': 'kui2', 'ǎi': 'ai3', 'cuì': 'cui4', 'zhè': 'zhe4', 'suǒ': 'suo3',
'tuò': 'tuo4', 'shuà': 'shua4', 'chuāng': 'chuang1', 'chōng': 'chong1',
'dìng': 'ding4', 'shài': 'shai4', 'bào': 'bao4', 'dàng': 'dang4',
'miē': 'mie1', 'qiū': 'qiu1', 'xiōng': 'xiong1', 'niū': 'niu1',
'jiǒng': 'jiong3', 'láng': 'lang2', 'mù': 'mu4', 'ráo': 'rao2',
'huǎng': 'huang3', 'sài': 'sai4', 'mǐn': 'min3', 'shùn': 'shun4',
'nián': 'nian2', 'kǎ': 'ka3', 'jie': 'jie', 'zǎi': 'zai3', 'piàn': 'pian4',
'láo': 'lao2', 'yǐn': 'yin3', 'huì': 'hui4', 'biě': 'bie3', 'cì': 'ci4',
'áng': 'ang2', 'fá': 'fa2', 'lǔ': 'lu3', 'nān': 'nan1', 'shǐ': 'shi3',
'lǎng': 'lang3', 'lòu': 'lou4', 'fǔ': 'fu3', 'tún': 'tun2', 'tiǎo': 'tiao3',
'shě': 'she3', 'nù': 'nu4', 'yǒu': 'you3', 'chāng': 'chang1', 'míng': 'ming2',
'cháo': 'chao2', 'jiē': 'jie1', 'shǎng': 'shang3', 'niú': 'niu2', 'mí': 'mi2',
'yàn': 'yan4', 'shà': 'sha4', 'qiàng': 'qiang4', 'zá': 'za2', 'qié': 'qie2',
'róng': 'rong2', 'kài': 'kai4', 'chàng': 'chang4', 'tǒu': 'tou3',
'tái': 'tai2', 'pèng': 'peng4', 'wú': 'wu2', 'tìng': 'ting4', 'le': 'le',
'děi': 'dei3', 'tíng': 'ting2', 'qǐn': 'qin3', 'dào': 'dao4', 'běn': 'ben3',
'féng': 'feng2', 'qiān': 'qian1', 'zhèn': 'zhen4', 'pò': 'po4', 'tuó': 'tuo2',
'āi': 'ai1', 'hāo': 'hao1', 'pù': 'pu4', 'fó': 'fo2', 'nòng': 'nong4',
'guì': 'gui4', 'tiě': 'tie3', 'rǎng': 'rang3', 'zha': 'zha', 'lóu': 'lou2',
'lián': 'lian2', 'bái': 'bai2', 'zhuāng': 'zhuang1', 'shū': 'shu1',
'dōu': 'dou1', 'hóu': 'hou2', 'huáng': 'huang2', 'chuō': 'chuo1',
'pèn': 'pen4', 'zhòu': 'zhou4', 'xiáo': 'xiao2', 'zhuó': 'zhuo2',
'wěng': 'weng3', 'qiē': 'qie1', 'yǔ': 'yu3', 'zhòng': 'zhong4',
'gāng': 'gang1', 'fiào': 'fiao4', 'chēng': 'cheng1', 'wa': 'wa', 'gǎi': 'gai3',
'nǎng': 'nang3', 'zǔ': 'zu3', 'lěi': 'lei3', 'dīng': 'ding1', 'biāo': 'biao1',
'jūn': 'jun1', 'jiě': 'jie3', 'e': 'e', 'yuàn': 'yuan4', 'zǔn': 'zun3',
'zhèng': 'zheng4', 'gēn': 'gen1', 'liú': 'liu2', 'zōng': 'zong1',
'páng': 'pang2', 'lüè': 'lüe4', 'cén': 'cen2', 'shéi': 'shei2',
'hāng': 'hang1', 'bǎo': 'bao3', 'qiǎ': 'qia3', 'pǎi': 'pai3',
'xiāng': 'xiang1', 'guǎi': 'guai3', 'yīn': 'yin1', 'hù': 'hu4',
'shěng': 'sheng3', 'héng': 'heng2', 'tiāo': 'tiao1', 'hǎn': 'han3',
'miào': 'miao4', 'gǎng': 'gang3', 'qià': 'qia4', 'rú': 'ru2', 'zàng': 'zang4',
'hài': 'hai4', 'duǒ': 'duo3', 'chuī': 'chui1', 'zé': 'ze2', 'sè': 'se4',
'cī': 'ci1', 'wǎng': 'wang3', 'luò': 'luo4', 'tóu': 'tou2', 'zhāng': 'zhang1',
'sǎ': 'sa3', 'liū': 'liu1', 'zhǒu': 'zhou3', 'zhě': 'zhe3', 'sūn': 'sun1',
'rēng': 'reng1', 'mò': 'mo4', 'huán': 'huan2', 'rén': 'ren2', 'xú': 'xu2',
'cuān': 'cuan1', 'mǒ': 'mo3', 'ān': 'an1', 'fǎ': 'fa3', 'xǔ': 'xu3',
'lē': 'le1', 'nǐ': 'ni3', 'jǐn': 'jin3', 'gá': 'ga2', 'lǒng': 'long3',
'miù': 'miu4', 'gàng': 'gang4', 'quē': 'que1', 'bǒ': 'bo3', 'kǎo': 'kao3',
'nié': 'nie2', 'xiáng': 'xiang2', 'ruí': 'rui2', 'kū': 'ku1', 'chǐ': 'chi3',
'xiá': 'xia2', 'ǎo': 'ao3', 'rěn': 'ren3', 'á': 'a2', 'zàn': 'zan4',
'xiū': 'xiu1', 'réng': 'reng2', 'sǔn': 'sun3', 'gào': 'gao4', 'èr': 'er4',
'lái': 'lai2', 'miāo': 'miao1', 'huái': 'huai2', 'jiōng': 'jiong1', 'xu': 'xu',
'liè': 'lie4', 'qǔ': 'qu3', 'yù': 'yu4', 'shuāng': 'shuang1', 'rèn': 'ren4',
'hé': 'he2', 'yě': 'ye3', 'lǎn': 'lan3', 'náo': 'nao2', 'cǔn': 'cun3',
'jiáo': 'jiao2', 'xì': 'xi4', 'fěn': 'fen3', 'yīng': 'ying1', 'duī': 'dui1',
'bàng': 'bang4', 'dèng': 'deng4', 'rè': 're4', 'mǎi': 'mai3', 'guī': 'gui1',
'yū': 'yu1', 'hàn': 'han4', 'hǎo': 'hao3', 'fěng': 'feng3', 'xuè': 'xue4',
'duàn': 'duan4', 'rún': 'run2', 'jǔ': 'ju3', 'yāo': 'yao1', 'jié': 'jie2',
'gè': 'ge4', 'dàn': 'dan4', 'pái': 'pai2', 'quàn': 'quan4', 'kuáng': 'kuang2',
'máng': 'mang2', 'xí': 'xi2', 'ràng': 'rang4', 'lāo': 'lao1', 'tì': 'ti4',
'wén': 'wen2', 'cuàn': 'cuan4', 'lie': 'lie', 'tàng': 'tang4', 'jì': 'ji4',
'má': 'ma2', 'wǎ': 'wa3', 'luán': 'luan2', 'xiàng': 'xiang4', 'pī': 'pi1',
'kuān': 'kuan1', 'zūn': 'zun1', 'yūn': 'yun1', 'āo': 'ao1', 'què': 'que4',
'lāng': 'lang1', 'mǎn': 'man3', 'sān': 'san1', 'tí': 'ti2', 'xīn': 'xin1',
'quān': 'quan1', 'chī': 'chi1', 'huǎn': 'huan3', 'xiòng': 'xiong4',
'chún': 'chun2', 'bo': 'bo', 'hàng': 'hang4', 'zhān': 'zhan1', 'bǎng': 'bang3',
'sǎo': 'sao3', 'dié': 'die2', 'yān': 'yan1', 'liáng': 'liang2', 'xǐ': 'xi3',
'zhēng': 'zheng1', 'biǎo': 'biao3', 'niáng': 'niang2', 'hòu': 'hou4',
'guāng': 'guang1', 'rù': 'ru4', 'jiān': 'jian1', 'mén': 'men2', 'tán': 'tan2',
'gān': 'gan1', 'xiā': 'xia1', 'bìn': 'bin4', 'mō': 'mo1', 'shí': 'shi2',
'xuān': 'xuan1', 'shuō': 'shuo1', 'da': 'da', 'dǎo': 'dao3', 'yú': 'yu2',
'fù': 'fu4', 'cūn': 'cun1', 'chěn': 'chen3', 'chuāi': 'chuai1', 'gāi': 'gai1',
'liáo': 'liao2', 'liǎn': 'lian3', 'sēn': 'sen1', 'tīng': 'ting1',
'guō': 'guo1', 'hūn': 'hun1', 'chen': 'chen', 'pēn': 'pen1', 'yǎ': 'ya3',
'xīng': 'xing1', 'pín': 'pin2', 'bān': 'ban1', 'wù': 'wu4', 'fēng': 'feng1',
'dǎn': 'dan3', 'jī': 'ji1', 'jià': 'jia4', 'nà': 'na4', 'li': 'li',
'tiān': 'tian1', 'pū': 'pu1', 'zuó': 'zuo2', 'qiǎng': 'qiang3', 'jǐ': 'ji3',
'dǒu': 'dou3', 'jīng': 'jing1', 'fǎn': 'fan3', 'gōu': 'gou1', 'gāo': 'gao1',
'sāi': 'sai1', 'zhóu': 'zhou2', 'jiǎ': 'jia3', 'niān': 'nian1', 'qiā': 'qia1',
'lòng': 'long4', 'sóng': 'song2', 'lèng': 'leng4', 'chí': 'chi2',
'dài': 'dai4', 'lán': 'lan2', 'gōng': 'gong1', 'ǒ': 'o3', 'shuā': 'shua1',
'zōu': 'zou1', 'shǔ': 'shu3', 'la': 'la', 'qiè': 'qie4', 'hú': 'hu2',
'jìn': 'jin4', 'cēng': 'ceng1', 'ba': 'ba', 'gòng': 'gong4', 'dòu': 'dou4',
'xiān': 'xian1', 'nài': 'nai4', 'sōu': 'sou1', 'chě': 'che3', 'tè': 'te4',
'ǒu': 'ou3', 'yè': 'ye4', 'lēng': 'leng1', 'cān': 'can1', 'duǎn': 'duan3',
'liǔ': 'liu3', 'tāi': 'tai1', 'hā': 'ha1', 'dǔn': 'dun3', 'liàn': 'lian4',
'zòng': 'zong4', 'a': 'a', 'yíng': 'ying2', 'cáng': 'cang2', 'wèn': 'wen4',
'sī': 'si1', 'kuò': 'kuo4', 'rán': 'ran2', 'tōng': 'tong1', 'māng': 'mang1',
'chē': 'che1', 'kuā': 'kua1', 'mì': 'mi4', 'zèn': 'zen4', 'cóng': 'cong2',
'cǎo': 'cao3', 'dā': 'da1', 'běi': 'bei3', 'tū': 'tu1', 'shàng': 'shang4',
'bó': 'bo2', 'jiǎn': 'jian3', 'tǒng': 'tong3', 'chà': 'cha4', 'guàn': 'guan4',
'wài': 'wai4', 'xiǎo': 'xiao3', 'guǐ': 'gui3', 'gē': 'ge1', 'cǐ': 'ci3',
'qiāo': 'qiao1', 'měng': 'meng3', 'lǎ': 'la3', 'zhǔ': 'zhu3', 'sā': 'sa1',
'bù': 'bu4', 'miè': 'mie4', 'rǎo': 'rao3', 'cú': 'cu2', 'nāo': 'nao1',
'shuān': 'shuan1', 'cāi': 'cai1', 'hōng': 'hong1', 'hēi': 'hei1',
'sēng': 'seng1', 'zī': 'zi1', 'zòu': 'zou4', 'lǐ': 'li3', 'rì': 'ri4',
'béng': 'beng2', 'nán': 'nan2', 'pán': 'pan2', 'dāo': 'dao1', 'tǔn': 'tun3',
'qìng': 'qing4', 'huí': 'hui2', 'te': 'te', 'lu': 'lu', 'mà': 'ma4',
'chuáng': 'chuang2', 'zhuǎng': 'zhuang3', 'bǔ': 'bu3', 'háo': 'hao2',
'dāng': 'dang1', 'līn': 'lin1', 'áo': 'ao2', 'sú': 'su2', 'cǎn': 'can3',
'kāng': 'kang1', 'piān': 'pian1', 'gén': 'gen2', 'cùn': 'cun4', 'hěn': 'hen3',
'wàn': 'wan4', 'pǔ': 'pu3', 'rǒng': 'rong3', 'huài': 'huai4', 'mú': 'mu2',
'chá': 'cha2', 'lǒu': 'lou3', 'jiàng': 'jiang4', 'xuǎn': 'xuan3', 'mǐ': 'mi3',
'dù': 'du4', 'fǎng': 'fang3', 'shèng': 'sheng4', 'yáo': 'yao2', 'ná': 'na2',
'xióng': 'xiong2', 'shǔn': 'shun3', 'kuī': 'kui1', 'shén': 'shen2',
'juē': 'jue1', 'céng': 'ceng2', 'lai': 'lai', 'dé': 'de2', 'ào': 'ao4',
'mái': 'mai2', 'zǐ': 'zi3', 'shòu': 'shou4', 'ǎ': 'a3', 'mèng': 'meng4',
'chēn': 'chen1', 'po': 'po', 'mān': 'man1', 'cèi': 'cei4', 'qióng': 'qiong2',
'kǒu': 'kou3', 'yào': 'yao4', 'shā': 'sha1', 'shào': 'shao4', 'yōng': 'yong1',
'kuāng': 'kuang1', 'shú': 'shu2', 'zhuàng': 'zhuang4', 'yē': 'ye1',
'gǎn': 'gan3', 'yī': 'yi1', 'lú': 'lu2', 'qiǔ': 'qiu3', 'huō': 'huo1',
'bà': 'ba4', 'cáo': 'cao2', 'ruó': 'ruo2', 'sháo': 'shao2', 'tào': 'tao4',
'chài': 'chai4', 'zhuā': 'zhua1', 'luǎn': 'luan3', 'tù': 'tu4', 'bú': 'bu2',
'fǒu': 'fou3', 'nuò': 'nuo4', 'sà': 'sa4', 'ò': 'o4', 'duò': 'duo4',
'zùn': 'zun4', 'lín': 'lin2', 'càn': 'can4', 'yōu': 'you1', 'yā': 'ya1',
'piè': 'pie4', 'tǎi': 'tai3', 'tòu': 'tou4', 'ài': 'ai4', 'lo': 'lo',
'péi': 'pei2', 'é': 'e2', 'qiǎn': 'qian3', 'kě': 'ke3', 'luǒ': 'luo3',
'lou': 'lou', 'chǎn': 'chan3', 'miàn': 'mian4', 'tǎn': 'tan3', 'yì': 'yi4',
'hē': 'he1', 'bēng': 'beng1', 'gǒng': 'gong3', 'wēn': 'wen1',
'qiāng': 'qiang1', 'péng': 'peng2', 'mǐng': 'ming3', 'jiào': 'jiao4',
'wāi': 'wai1', 'bēi': 'bei1', 'guā': 'gua1', 'yǔn': 'yun3', 'ruò': 'ruo4',
'tú': 'tu2', 'chǎ': 'cha3', 'xǐng': 'xing3', 'nìng': 'ning4', 'pān': 'pan1',
'kuàng': 'kuang4', 'yǒng': 'yong3', 'yǎng': 'yang3', 'wǒ': 'wo3',
'zěn': 'zen3', 'zā': 'za1', 'chóu': 'chou2', 'lài': 'lai4', 'nuǎn': 'nuan3',
'piáo': 'piao2', 'tà': 'ta4', 'wà': 'wa4', 'gù': 'gu4', 'pèi': 'pei4',
'chū': 'chu1', 'chāi': 'chai1', 'zhěn': 'zhen3', 'jiū': 'jiu1', 'wǔ': 'wu3',
'sì': 'si4', 'pá': 'pa2', 'nín': 'nin2', 'còu': 'cou4', 'cuǐ': 'cui3',
'guāi': 'guai1', 'xué': 'xue2', 'èn': 'en4', 'niàn': 'nian4', 'yòng': 'yong4',
'kāi': 'kai1', 'luo': 'luo', 'zhái': 'zhai2', 'zhuī': 'zhui1', 'cào': 'cao4',
'chuā': 'chua1', 'cǎi': 'cai3', 'shuàn': 'shuan4', 'wāng': 'wang1',
'zuì': 'zui4', 'fān': 'fan1', 'hèng': 'heng4', 'lóng': 'long2', 'cǎ': 'ca3',
'ái': 'ai2', 'cā': 'ca1', 'bǐng': 'bing3', 'gàn': 'gan4', 'zèng': 'zeng4',
'shēn': 'shen1', 'jiāng': 'jiang1', 'dáo': 'dao2', 'guó': 'guo2',
'shǎi': 'shai3', 'chè': 'che4', 'shè': 'she4', 'chái': 'chai2', 'dú': 'du2',
'yún': 'yun2', 'wā': 'wa1', 'bāo': 'bao1', 'kē': 'ke1', 'ròu': 'rou4',
'hǔ': 'hu3', 'yìng': 'ying4', 'kòng': 'kong4', 'jiǔ': 'jiu3', 'shāi': 'shai1',
'chǒu': 'chou3', 'zhǒng': 'zhong3', 'piǎo': 'piao3', 'qué': 'que2',
'kàng': 'kang4', 'kuǎi': 'kuai3', 'kōu': 'kou1', 'shāng': 'shang1',
'bai': 'bai', 'jù': 'ju4', 'zú': 'zu2', 'chuài': 'chuai4', 'biàn': 'bian4',
'sāo': 'sao1', 'shàn': 'shan4', 'gǔn': 'gun3', 'xūn': 'xun1', 'mǎ': 'ma3',
'sǐ': 'si3', 'zēng': 'zeng1', 'qīng': 'qing1', 'ē': 'e1', 'fén': 'fen2',
'duō': 'duo1', 'tǐng': 'ting3', 'shì': 'shi4', 'suān': 'suan1', 'cè': 'ce4',
'juě': 'jue3', 'pó': 'po2', 'dì': 'di4', 'chén': 'chen2', 'mó': 'mo2',
'zhēn': 'zhen1', 'zhuǎn': 'zhuan3', 'mìng': 'ming4', 'léng': 'leng2',
'pào': 'pao4', 'qí': 'qi2', 'guàng': 'guang4', 'pō': 'po1', 'pǎo': 'pao3',
'fàng': 'fang4', 'yí': 'yi2', 'wēng': 'weng1', 'gā': 'ga1', 'ne': 'ne',
'pà': 'pa4', 'cù': 'cu4', 'lùn': 'lun4', 'qú': 'qu2', 'bèng': 'beng4',
'fū': 'fu1', 'zuǒ': 'zuo3', 'miáo': 'miao2', 'chù': 'chu4', 'nì': 'ni4',
'zuǎn': 'zuan3', 'zhù': 'zhu4', 'xiē': 'xie1', 'lǚ': 'lü3', 'gǒu': 'gou3',
'ma': 'ma', 'hǎ': 'ha3', 'qiáo': 'qiao2', 'xǐn': 'xin3', 'hèn': 'hen4',
'liàng': 'liang4', 'tāo': 'tao1', 'yá': 'ya2', 'jiǎo': 'jiao3', 'pǐn': 'pin3',
'shuò': 'shuo4', 'yǎn': 'yan3', 'nǚ': 'nü3', 'duó': 'duo2', 'hán': 'han2',
'yé': 'ye2', 'xù': 'xu4', 'liù': 'liu4', 'dǔ': 'du3', 'lā': 'la1',
'diǎo': 'diao3', 'lōu': 'lou1', 'jùn': 'jun4', 'huān': 'huan1',
'néng': 'neng2', 'niàng': 'niang4', 'lǘ': 'lü2', 'cái': 'cai2', 'shuǐ': 'shui3',
'dūn': 'dun1', 'wèi': 'wei4', 'huǒ': 'huo3', 'mǎng': 'mang3', 'shē': 'she1',
'kàn': 'kan4', 'róu': 'rou2', 'shōu': 'shou1', 'duān': 'duan1', 'cāo': 'cao1',
'qiú': 'qiu2', 'zhài': 'zhai4', 'hān': 'han1', 'táng': 'tang2',
'zhuàn': 'zhuan4', 'zhe': 'zhe', 'chǔ': 'chu3', 'ó': 'o2', 'shǎn': 'shan3',
'kòu': 'kou4', 'suǐ': 'sui3', 'nèn': 'nen4', 'fáng': 'fang2', 'kōng': 'kong1',
'mài': 'mai4', 'āng': 'ang1', 'zhuāi': 'zhuai1', 'xī': 'xi1', 'zhāi': 'zhai1',
'yuě': 'yue3', 'nǜ': 'nü4', 'chān': 'chan1', 'gèng': 'geng4', 'men': 'men',
'hè': 'he4', 'kā': 'ka1', 'shù': 'shu4', 'zuǐ': 'zui3', 'niǎo': 'niao3',
'kù': 'ku4', 'lèi': 'lei4', 'lǎo': 'lao3', 'nàn': 'nan4', 'huāng': 'huang1',
'xùn': 'xun4', 'sōng': 'song1', 'chèng': 'cheng4', 'nā': 'na1',
'xiǎng': 'xiang3', 'huā': 'hua1', 'jiàn': 'jian4', 'zhǎn': 'zhan3',
'xín': 'xin2', 'qǐng': 'qing3', 'lěng': 'leng3', 'diǎn': 'dian3',
'chuǎng': 'chuang3', 'zhuǎi': 'zhuai3', 'wèng': 'weng4', 'ruì': 'rui4',
'nī': 'ni1', 'náng': 'nang2', 'shuì': 'shui4', 'wēi': 'wei1', 'pì': 'pi4',
'màn': 'man4', 'ya': 'ya', 'káng': 'kang2', 'ěr': 'er3', 'biào': 'biao4',
'huǐ': 'hui3', 'gùn': 'gun4', 'shuǎ': 'shua3', 'niù': 'niu4', 'kuǎn': 'kuan3',
'na': 'na', 'zǎo': 'zao3', 'zhōng': 'zhong1', 'wá': 'wa2', 'ēn': 'en1',
'záo': 'zao2', 'niào': 'niao4', 'fú': 'fu2', 'lí': 'li2', 'tī': 'ti1',
'tuān': 'tuan1', 'qiàn': 'qian4', 'qín': 'qin2', 'pàn': 'pan4', 'qún': 'qun2',
'xìn': 'xin4', 'zū': 'zu1', 'qù': 'qu4', 'yùn': 'yun4', 'shuǎi': 'shuai3',
'chōu': 'chou1', 'dēng': 'deng1', 'lū': 'lu1', 'piǎn': 'pian3', 'mín': 'min2',
'ēng': 'eng1', 'sàng': 'sang4', 'zào': 'zao4', 'tùn': 'tun4', 'luō': 'luo1',
'zhà': 'zha4', 'tuǒ': 'tuo3', 'dān': 'dan1', 'xiàn': 'xian4', 'kěn': 'ken3',
'mā': 'ma1', 'jiāo': 'jiao1', 'kǔ': 'ku3', 'chéng': 'cheng2', 'máo': 'mao2',
'tóng': 'tong2', 'biān': 'bian1', 'sào': 'sao4', 'è': 'e4', 'gé': 'ge2',
'lìn': 'lin4', 'dǒng': 'dong3', 'jué': 'jue2', 'chàn': 'chan4', 'wò': 'wo4',
'shuí': 'shui2', 'pēng': 'peng1', 'tuō': 'tuo1', 'mèi': 'mei4', 'zhì': 'zhi4',
'bì': 'bi4', 'guà': 'gua4', 'tuán': 'tuan2', 'píng': 'ping2', 'dǎng': 'dang3',
'wáng': 'wang2', 'huá': 'hua2', 'tǔ': 'tu3', 'piào': 'piao4', 'xiǎn': 'xian3',
'cháng': 'chang2', 'lù': 'lu4', 'xié': 'xie2', 'niè': 'nie4', 'bīng': 'bing1',
'qī': 'qi1', 'zhǎi': 'zhai3', 'dēi': 'dei1', 'gà': 'ga4', 'xìng': 'xing4',
'fán': 'fan2', 'nüè': 'nüe4', 'pīng': 'ping1', 'zì': 'zi4', 'zhuō': 'zhuo1',
'bié': 'bie2', 'niē': 'nie1', 'nǔ': 'nu3', 'pén': 'pen2', 'lēi': 'lei1',
'shǎ': 'sha3', 'chuàn': 'chuan4', 'cí': 'ci2', 'gài': 'gai4', 'kǎn': 'kan3',
'sū': 'su1', 'làn': 'lan4', 'nǎn': 'nan3', 'zǎng': 'zang3', 'cēn': 'cen1',
'tēng': 'teng1', 'mǎo': 'mao3', 'tiē': 'tie1', 'pàng': 'pang4', 'guò': 'guo4',
'bài': 'bai4', 'qián': 'qian2', 'mī': 'mi1', 'juān': 'juan1', 'zuī': 'zui1',
'suí': 'sui2', 'diān': 'dian1', 'zhé': 'zhe2', 'qiá': 'qia2', 'là': 'la4',
'qiào': 'qiao4', 'sǒu': 'sou3', 'dǎi': 'dai3', 'jiù': 'jiu4', 'hà': 'ha4',
'fa': 'fa', 'móu': 'mou2', 'chǎi': 'chai3', 'diàn': 'dian4', 'wān': 'wan1',
'rāng': 'rang1', 'kuì': 'kui4', 'shang': 'shang', 'xià': 'xia4', 'zan': 'zan',
'bō': 'bo1', 'háng': 'hang2', 'shéng': 'sheng2', 'póu': 'pou2', 'lá': 'la2',
'zhàng': 'zhang4', 'cāng': 'cang1', 'níng': 'ning2', 'guǎn': 'guan3',
'kǎi': 'kai3', 'lǐng': 'ling3', 'tiè': 'tie4', 'chòu': 'chou4',
'xuán': 'xuan2', 'shǒu': 'shou3', 'qìn': 'qin4', 'pài': 'pai4',
'zhōu': 'zhou1', 'nuó': 'nuo2', 'nèi': 'nei4', 'bǎ': 'ba3', 'yà': 'ya4',
'guǒ': 'guo3', 'nǎ': 'na3', 'guān': 'guan1', 'lǜ': 'lü4', 'zháo': 'zhao2',
'zhǔn': 'zhun3', 'duì': 'dui4', 'mián': 'mian2', 'wàng': 'wang4',
'zhuài': 'zhuai4', 'zéi': 'zei2', 'bū': 'bu1', 'bā': 'ba1', 'tǎo': 'tao3',
'diǎ': 'dia3', 'qīn': 'qin1', 'kuài': 'kuai4', 'cuó': 'cuo2', 'rào': 'rao4',
'ōu': 'ou1', 'cuò': 'cuo4', 'hén': 'hen2', 'piē': 'pie1', 'nún': 'nun2',
'wéi': 'wei2', 'ní': 'ni2', 'yàng': 'yang4', 'chuǎn': 'chuan3',
'xíng': 'xing2', 'nǐng': 'ning3', 'shān': 'shan1', 'miǎo': 'miao3',
'dī': 'di1', 'gèn': 'gen4', 'líng': 'ling2', 'gǔ': 'gu3', 'zhí': 'zhi2',
'pián': 'pian2', 'huai': 'huai', 'guǎ': 'gua3', 'bèi': 'bei4', 'kùn': 'kun4',
'bī': 'bi1', 'kuǐ': 'kui3', 'hún': 'hun2', 'xuē': 'xue1', 'mèn': 'men4',
'tiáo': 'tiao2', 'gǎo': 'gao3', 'xiù': 'xiu4', 'cōng': 'cong1', 'cài': 'cai4',
'nào': 'nao4', 'dū': 'du1', 'hǎi': 'hai3', 'fēn': 'fen1', 'liē': 'lie1',
'xiāo': 'xiao1', 'tiàn': 'tian4', 'zāo': 'zao1', 'qūn': 'qun1',
'zhāo': 'zhao1', 'zhǎo': 'zhao3', 'bei': 'bei', 'chuǎi': 'chuai3',
'chú': 'chu2', 'fèng': 'feng4', 'lōng': 'long1', 'dùn': 'dun4', 'fā': 'fa1',
'yǐng': 'ying3', 'wěn': 'wen3', 'hào': 'hao4', 'lūn': 'lun1', 'yǎo': 'yao3',
'juè': 'jue4', 'jú': 'ju2', 'suō': 'suo1', 'pěng': 'peng3', 'zhē': 'zhe1',
'zhuǎ': 'zhua3', 'tàn': 'tan4', 'kāo': 'kao1', 'sǎng': 'sang3', 'kào': 'kao4',
'kuǎng': 'kuang3', 'jiǎng': 'jiang3', 'tǎng': 'tang3', 'hēng': 'heng1',
'zāi': 'zai1', 'chuí': 'chui2', 'biǎn': 'bian3', 'lìng': 'ling4',
'nǎo': 'nao3', 'wū': 'wu1', 'gě': 'ge3', 'huó': 'huo2', 'xiě': 'xie3',
'hāi': 'hai1', 'xū': 'xu1', 'wǎi': 'wai3', 'nú': 'nu2', 'jí': 'ji2',
'bǎn': 'ban3', 'táo': 'tao2', 'qiáng': 'qiang2', 'lè': 'le4'}
